
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Dec 19 18:18:34 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMICOLON = 17;
  public static final int PLUS = 10;
  public static final int INT = 3;
  public static final int CHAR = 4;
  public static final int LEFTPAR = 12;
  public static final int RIGHTCURLYPAR = 15;
  public static final int RIGHTPAR = 13;
  public static final int COLON = 19;
  public static final int ID = 8;
  public static final int COMMA = 18;
  public static final int LEFTCURLYPAR = 14;
  public static final int FLOAT = 5;
  public static final int EOF = 0;
  public static final int WHEN = 7;
  public static final int MAIN = 2;
  public static final int MINUS = 11;
  public static final int CONST = 9;
  public static final int CASE = 6;
  public static final int error = 1;
  public static final int ASSIGN = 16;
}

