
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 11 20:10:31 CET 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMICOLON = 16;
  public static final int PLUS = 8;
  public static final int INT = 3;
  public static final int CHAR = 4;
  public static final int LEFTPAR = 11;
  public static final int INTCONST = 19;
  public static final int RIGHTPAR = 12;
  public static final int COLON = 17;
  public static final int ID = 18;
  public static final int COMMA = 15;
  public static final int FLOAT = 5;
  public static final int EOF = 0;
  public static final int CHARCONST = 20;
  public static final int WHEN = 7;
  public static final int LEFTBRA = 13;
  public static final int MAIN = 2;
  public static final int MINUS = 9;
  public static final int CASE = 6;
  public static final int error = 1;
  public static final int ASSIGN = 10;
  public static final int RIGHTBRA = 14;
  public static final int FLOATCONST = 21;
}

